import { VictorinaData } from '../models/victorina-data';

export const DefaultVictorinaData: VictorinaData[] = [
  {
    id: 1,
    title: 'Halloween',
    image: 'img-halloween.jpg',
    questions: [
      {
        id: 1,
        points: 1,
        question: 'test',
        answered: false,
        image: 'Haloween-1pt.jpg',
        answerImage: 'Haloween-1pt-answer.jpg',
      },
      {
        id: 2,
        points: 2,
        question: 'test',
        answered: false,
        image: 'Haloween-2pt.jpg',
        answerImage: 'Haloween-2pt-answer.jpg',
      },
      {
        id: 3,
        points: 3,
        question: 'test',
        answered: false,
        image: 'Haloween-3pt.jpg',
        answerImage: 'Haloween-3pt-answer.jpg',
      },
    ],
  },
  {
    id: 2,
    title: 'Gyvūnai',
    image: 'img-gyvunai.jpg',
    questions: [
      {
        id: 1,
        points: 1,
        question: 'test',
        answered: false,
        image: 'Gyvunai-1pt.jpg',
        answerImage: 'Gyvunai-1pt-answer.jpg',
      },
      {
        id: 2,
        points: 2,
        question: 'test',
        answered: false,
        image: 'Gyvunai-2pt.jpg',
        answerImage: 'Gyvunai-2pt-answer.jpg',
      },
      {
        id: 3,
        points: 3,
        question: 'test',
        answered: false,
        image: 'Gyvunai-3pt.jpg',
        answerImage: 'Gyvunai-3pt-answer.jpg',
      },
    ],
  },
  {
    id: 3,
    title: 'Muzika',
    image: 'img-muzika.jpg',
    questions: [
      {
        id: 1,
        points: 1,
        question: 'test',
        answered: false,
        image: 'Muzika-1pt.jpg',
        answerImage: 'Muzika-1pt-answer.jpg',
      },
      {
        id: 2,
        points: 2,
        question: 'test',
        answered: false,
        image: 'Muzika-2pt.jpg',
        answerImage: 'Muzika-2pt-answer.jpg',
      },
      {
        id: 3,
        points: 3,
        question: 'test',
        answered: false,
        image: 'Muzika-3pt.jpg',
        answerImage: 'Muzika-3pt-answer.jpg',
      },
    ],
  },
  {
    id: 4,
    title: 'Serialai ir filmai',
    image: 'img-serialai-filmai.jpg',
    questions: [
      {
        id: 1,
        points: 1,
        question: 'test',
        answered: false,
        image: 'Filmai-1pt.jpg',
        answerImage: 'Filmai-1pt-answer.jpg',
      },
      {
        id: 2,
        points: 2,
        question: 'test',
        answered: false,
        image: 'Filmai-2pt.jpg',
        answerImage: 'Filmai-2pt-answer.jpg',
      },
      {
        id: 3,
        points: 3,
        question: 'test',
        answered: false,
        image: 'Filmai-3pt.jpg',
        answerImage: 'Filmai-3pt-answer.jpg',
      },
    ],
  },
  {
    id: 5,
    title: 'Programavimas',
    image: 'img-programavimas.jpg',
    questions: [
      {
        id: 1,
        points: 1,
        question: 'test',
        answered: false,
        image: 'Programavimas-1pt.jpg',
        answerImage: 'Programavimas-1pt-answer.jpg',
      },
      {
        id: 2,
        points: 2,
        question: 'test',
        answered: false,
        image: 'Programavimas-2pt.jpg',
        answerImage: 'Programavimas-2pt-answer.jpg',
      },
      {
        id: 3,
        points: 3,
        question: 'test',
        answered: false,
        image: 'Programavimas-3pt.jpg',
        answerImage: 'Programavimas-3pt-answer.jpg',
        answer: 'CEASARCIPHER',
      },
    ],
  },
  {
    id: 6,
    title: 'Menas',
    image: 'img-menas.jpg',
    questions: [
      {
        id: 1,
        points: 1,
        question: 'test',
        answered: false,
        image: 'Menas-1pt.jpg',
        answerImage: 'Menas-1pt-answer.jpg',
      },
      {
        id: 2,
        points: 2,
        question: 'test',
        answered: false,
        image: 'Menas-2pt.jpg',
        answerImage: 'Menas-2pt-answer.jpg',
      },
      {
        id: 3,
        points: 3,
        question: 'test',
        answered: false,
        image: 'Menas-3pt.jpg',
      },
    ],
  },
  {
    id: 7,
    title: 'Žaidimai',
    image: 'img-zaidimai.jpg',
    questions: [
      { id: 1, points: 1, question: 'test', answered: false },
      {
        id: 2,
        points: 2,
        question: 'test',
        answered: false,
        image: 'Zaidimai-2pt.jpg',
        answerImage: 'Zaidimai-2pt-answer.jpg',
      },
      {
        id: 3,
        points: 3,
        question: 'test',
        answered: false,
        image: 'Zaidimai-3pt.jpg',
      },
    ],
  },
  {
    id: 8,
    title: 'Mystery',
    image: 'img-mystery.jpg',
    questions: [
      {
        id: 1,
        points: 1,
        question: 'test',
        answered: false,
        image: 'Mystery-1pt.jpg',
        answerImage: 'Mystery-1pt-answer.jpg',
      },
      {
        id: 2,
        points: 2,
        question: 'test',
        answered: false,
        image: 'Mystery-2pt.jpg',
        answerImage: 'Mystery-2pt-answer.jpg',
      },
      {
        id: 3,
        points: 3,
        question: 'test',
        answered: false,
        image: 'mystery-1pt.jpg',
      },
    ],
  },
];
